(* Go (gopls) helpers for the LSP client.
 *
 * Extract the type string from a gopls hover response and parse it
 * into AST_generic.type_.
 *
 * coupling: the hover content is generated by gopls in:
 *   https://github.com/golang/tools/blob/master/gopls/internal/golang/hover.go
 * formatHover() wraps signatures in ```go ... ``` code fences.
 *
 * gopls hover format (markdown with code fences):
 *
 * For variables like 'x := 42':
 *   "```go\nvar x int\n```"
 *   We extract: "int"  (strip "var NAME ")
 *
 * For short declarations like 'sum := Add(x, 1)':
 *   "```go\nvar sum int\n```"
 *   We extract: "int"
 *
 * For functions like 'func Add(a int, b int) int':
 *   "```go\nfunc Add(a int, b int) int\n```\n\nAdd returns the sum..."
 *   We extract: "func(int, int) int"  (the function type)
 *
 * For packages:
 *   "```go\npackage fmt\n```\n\n..."
 *   No type to extract.
 *)

open Common
module G = AST_generic

let project_root_marker = "go.mod"
let language_id = "go"
let server_cmd (_caps : < Cap.exec ; .. >) = "gopls"

let clean_hover s =
  (* Step 1: strip ```go ... ``` code fences.
   * e.g. "```go\nvar x int\n```\n\nDocumentation..."
   *   -> "var x int\n\nDocumentation..."
   *)
  let s =
    if s =~ "^```go\n\\(.*\\)" then Common.matched1 s else s
  in
  let s = Str.global_replace (Str.regexp "```$") "" s in

  (* Step 2: remove documentation after separators.
   * e.g. "var x int\n\nDocumentation..."
   *   -> "var x int"
   *)
  let s =
    match Str.bounded_split (Str.regexp "\n---\n\\|\n\n") s 2 with
    | type_part :: _ -> type_part
    | [] -> s
  in

  (* Step 3: collapse newlines *)
  let s = Str.global_replace (Str.regexp "\n") " " s in
  let s = String.trim s in

  (* Step 4: extract the type from the declaration.
   * "var x int"       -> "int"
   * "var p *string"   -> "*string"
   * "func Add(a int, b int) int" -> keep as-is for parse_type
   *)
  if s =~ "^var [a-zA-Z_][a-zA-Z_0-9]* \\(.*\\)" then Common.matched1 s
  else s

(* Try to parse a Go type string by wrapping it as "var _x TYPE"
 * and extracting the type from the resulting variable declaration.
 * A bare type like "int" is parsed as an expression by Go's sgrep
 * parser, not as a type, so we need this wrapper trick. *)
let try_parse_go_type str =
  try
    let wrapped = "var _x " ^ str in
    let any = Parse_go.any_of_string wrapped in
    (* Convert through the generic AST and extract the type.
     * "var _x int" → S (DefStmt (_, VarDef { vtype = Some int })) *)
    let generic = Go_to_generic.any any in
    match generic with
    | G.S { G.s = G.DefStmt (_, G.VarDef { G.vtype = Some ty; _ }); _ } ->
        Some ty
    | _x ->
        None
  with _exn -> None

(* Parse a cleaned gopls hover string into AST_generic.type_. *)
let parse_type s =
  match try_parse_go_type s with
  | Some ty -> ty
  | None ->
      failwith (spf "LSP_client: cannot parse Go type from: %s" s)

let lsp_lang : LSP_lang.t = {
  server_cmd = (fun caps -> server_cmd caps);
  language_id;
  project_root_marker;
  clean_hover;
  parse_type;
  needs_warmup = false;
}
